version: 2.1

references:
  workspace_root: &workspace_root
    ~/workspace

orbs:
  npm: sugarshin/npm@0.1.3

executors:
  nodejs:
    working_directory: *workspace_root
    docker:
      - image: circleci/node:12.13.0

jobs:
  test:
    executor:
      name: nodejs
    steps:
      - checkout
      - npm/install
      - run:
          name: Validate configurations
          command: npm test

workflows:
  test_and_publish:
    jobs:
      - test
      - npm/release:
          executor: nodejs
          workspace-root: *workspace_root
          flags: --access=public
          tagging: true
          ssh-fingerprints: fb:73:06:7d:cd:ca:97:f4:ec:bd:4d:c5:ab:18:50:2b
          requires:
            - test
          filters:
            branches:
              only: master
